version: '3.8'
services:
  mongodb:
    image: mongo:${MONGO_DB_VERSION}
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
volumes:
  data: